# High level
vehicle: 'vehicles/test_vehicle.yaml' #.yaml
simulation_type: 'single_run' # single_run, sweep
evaluation_mode: 'endurance' # endurance

# Performance envelope
velocity_range: [10,10,1] # m/s, m/s , N
body_slip_range: [-0.26,0.26, 30] # rad, rad , N
steered_angle_range: [-0.26,0.26, 30] # rad, rad , N


# Paths
paths:
  endurance: 
    file: '2019_endurance.svg' # .svg
    length: 2000.0 # meters
    steps: 1000 # integer
    unique_radii: 25 # integer
