front_shock_stiffness: 40 # N/mm
front_shock_damping: 0.23529411764
front_shock_ride_compression: 20.47
# front_shock_ride_compression: 0
rear_shock_stiffness: 40
rear_shock_damping: 0.23529411764
rear_shock_ride_compression: 21.00
# rear_shock_ride_compression: 0
vehicle_mass: 270
vehicle_inertia: [[132.29,0,0],[0,32.93,0],[0,0,120.79]]
center_of_mass: [-767.5, 0, 100]

